### ISSUE TITLE
Hosting patches for n0 Games

### ISSUE THREAD

**Issue by turke** [mon/BemaniPatcher#72]
Theres no need, only opens up potential issues for yourself and everyone else. Whatever you add now will be irrelevant whenever the next update comes. "Look what we have, but you can't use it, sorry"

**Comment by mon** [comment]
I am going the low-effort, maximum-value approach of accepting any pull request for a game that has a sane looking diff. It's much less effort than dealing with politics and remembering release dates. I don't have any n-0 data that's on bemanipatcher, so there's no personal incentive there.

I just want easy patches for all, regardless of your affiliation.

**Comment by mon** [comment]
In the same vein, the person who submitted the n-0 edits has come under some flak and submitted a PR to remove them - I'm honouring this.

**Comment by Poliwrath** [comment]
Since most hex edits for similar games are usually the same (except for addresses), would it be easier to just do pattern matching for them (or whatever the term is called)? No need to have individual game pages, unless there's a hex edit that can't be found this way, for example I think the DDR A dark BG hex edit is like this

¯\\_(ツ)_/¯

**Comment by mon** [comment]
Whilst valid, not all hex edits are signature-able. I'm certainly keen for it, as long as other people do the signatures.
